### ISSUE TITLE
Markdown processor?

### ISSUE THREAD

**Issue by rvinay88** [bjankord/Style-Guide-Boilerplate#15]
Hi, thanks for the tool. IMO, this is more flexible than other tools which bake in the documentation inside of the CSS, which I personally dislike. However, is there anyway we can include a markdown processor for the docs? As the docs require code blocks? I'd be happy to send a PR but I haven't worked in PHP before

**Comment by johnstonian** [comment]
+1

**Comment by bjankord** [comment]
I've played around with getting markdown documentation working, but have not had any success with it so far. 

What I'd like to do is check if files in the doc directory are .html or .md files and then handle accordingly. If it is and .html file, render it as is, if it is a .md file, process it and then render it to the page.

**Comment by johnstonian** [comment]
sounds like a great idea. Rendering the .md file differently than an .html file. Maybe something like Parsedown would work? https://github.com/erusev/parsedown

**Comment by bjankord** [comment]
I've got this working locally with parsedown. Need to do some more testing. I'm planning on a minor release soon with markdown support for documentation once I finish testing.

**Comment by bjankord** [comment]
Markdown support for docs has landed v3.2.0. You can continue using .html files for docs if you want. If you switch your docs to markdown files, style-guide-boilerplate will render/parse them instead of rendering your .html doc files.

**Comment by johnstonian** [comment]
+1! Thanks, this is great!
