### ISSUE TITLE
Static Site Generation

### ISSUE THREAD

**Issue by cpoteet** [bjankord/Style-Guide-Boilerplate#17]
Hey I love this generator. It's my favorite so far due to its simplicity and versatility. One thing that would be great is to generate a static site from the PHP that could more easily be handed off to customers. Is something like that possible?

**Comment by bjankord** [comment]
Generating a static site is a direction I'd like to head in for this project. I'm unsure if I want to do that with PHP or use something like node/grunt. [Assemble.js](http://assemble.io/) is a project I've been exploring for static site generation.

**Comment by cpoteet** [comment]
That would be great. I think it's the only thing keeping it back a bit at this point. Pattern Lab does static site generation, but man does that thing have a lot of overhead.

The other "wish list" item would be the ability to create more sections of the guide such as voice/tone, templates, etc. I know I can adjust the PHP to do it, but building that flexibility in where I can just add a folder would be great.

**Comment by lostsatellites** [comment]
I second the request for static output. This has been an awesome resource and that'd be icing on the cake.

**Comment by johnstonian** [comment]
Agreed, this would be a wonderful feature for the project. In the meantime, one could run ```wget``` to scrape the site and generate static pages. I've done this for a few clients in the past and it works well.

```
$ wget \
     --recursive \
     --no-clobber \
     --page-requisites \
     --html-extension \
     --convert-links \
     --restrict-file-names=windows \
     --domains website.org \
     --no-parent \
         www.website.org/tutorials/html/
```

Got the command from this link: http://www.linuxjournal.com/content/downloading-entire-web-site-wget. An oldie, but a goodie!

**Comment by bjankord** [comment]
I took a look to see how this could be added. I agree it would be an awesome feature, the simplest way I've found to do this is to compile on the command line with `php index.php > index.html`

Does running this on the CLI work for you?

**Comment by bjankord** [comment]
Static site generation How To has been noted in [README.md](https://github.com/bjankord/Style-Guide-Boilerplate#generating-static-html-style-guide)

**Comment by johnstonian** [comment]
+1
