### ISSUE TITLE
Code Selection stopped working at some point

### ISSUE THREAD

**Issue by englishextra** [bjankord/Style-Guide-Boilerplate#21]
I've been trying to build a styleguide using this brilliant work.

But at some point selection of the code stopped working.

Firefox with Web Developer addon wont show an error when  clicking Copy Source button.

Would you advise where to move on?

The live page/patient - https://englishextra.github.io/pages/styleguide.html
The Repo here https://github.com/englishextra/englishextra.github.io/blob/master/pages/styleguide.html

After a couple of hours debugging I found that your original template html markup gets selected visually.

Mine doesn't - the w3c validator only warns about new functionality but the rest is ok.

**Comment by bjankord** [comment]
Looking at [this page](https://github.com/englishextra/englishextra.github.io/blob/master/pages/styleguide.html), it looks like in your code you have this markup structure

``` html
<div class="sg-source sg-animated">
  <pre class="prettyprint lang-css linenums line-numbers">
    ...
  </pre>
</div>
```

The code examples are missing the btn that triggers the code selection. If you add this line into that code: ` <a class="sg-btn sg-btn--select" href="#">Copy Source</a>` and have the JS from Style Guide Boilerplate, it should work as intended.

Style Guide Boilerplate code example markup:
``` html
<div class="sg-source sg-animated">
   <a class="sg-btn sg-btn--select" href="#">Copy Source</a>
   <pre class="prettyprint linenums prettyprinted">
     ...
   </pre>
</div>
```

**Comment by englishextra** [comment]
I removed code selection feature because it wouldn't work at all if you format your code not the way you do in your template. Well I'm sure that you are aware of that. Try to reformat html markup of your template and selectNodeContents will stop working. Sure thing the pre stuff is left intact. So the problem lies in indention. So long as I would prefer to have my markup consistent that is indented with tabs like aptana does automatically, i will have to live without this option of selectNodeContents. Thanks anyway for the reply.

**Comment by bjankord** [comment]
If you show me the markup you had trouble with, I may be able to help out some more. The "Copy Source" button highlights the content of next sibling element after the "Copy Source" button based on this [line](https://github.com/bjankord/Style-Guide-Boilerplate/blob/master/js/sg-scripts.js#L81).

So if the pre element that displays the code is not the next sibling element following the "Copy Source" button, that JavaScript will not work as expected.

**Comment by englishextra** [comment]
the reproducing sample is there https://englishextra.github.io/pages/styleguide.html

Actually I'm sure that the tab indent is to blame. and this was mentioned on StackOverflow. So you're right. And the trouble is that i cant just throw away my coding style and remove indent tabs. Dead-end.

**Comment by bjankord** [comment]
I'm planning to update the code selection JS to use [clipboard.js](http://zenorocha.github.io/clipboard.js/). I'm curious if that will work better for your use case. I'll test it with different tab indents. If you come across the SO link, I'd be interested to check it out.

**Comment by englishextra** [comment]
Thanks for reply. Will get over this idea/solution as soon as I am able to.
