### ISSUE TITLE
scandir picks up hidden system files

### ISSUE THREAD

**Issue by yellowled** [bjankord/Style-Guide-Boilerplate#30]
Most Unix-/Linux-type operating systems (including OS X) produce hidden system files usually starting with a dot in the file's name (e.g. the infamous `.DS_Store` on OS X). PHP's `scandir` picks these up as well, but they are not excluded by `if ($file != '.' && $file != '..')` in `functions.php`.

Ideally, the `*FilesInFolder` functions should probably exclude any file name that starts with a `.`.

**Comment by bjankord** [comment]
Agreed, will plan on adding this over the weekend.

**Comment by bjankord** [comment]
Thanks @yellowled. Added a `.DS_Store` file to the `markup` directory and sure enough, it was being picked up by scandir and was not filtered out by the if statement.

I've [updated](https://github.com/bjankord/Style-Guide-Boilerplate/commit/74d461f66b0e76eacede927adabe934d80af6022) the scandir check to skip files that start with a `.`

**Comment by yellowled** [comment]
:+1:
