### ISSUE TITLE
sg-nav-group link styles

### ISSUE THREAD

**Issue by yellowled** [bjankord/Style-Guide-Boilerplate#31]
`css/sg-styles.css` only defines `.sg-nav-group a` and `.sg-nav-group a:hover`. If a user replaces `css/styles.css` with a project stylesheet that defines `a:visited` and `a:focus`, this might look strange.

![screenshot 2015-12-16 13 44 02](https://cloud.githubusercontent.com/assets/326223/11841138/63c0b658-a3fb-11e5-8962-f263ed789347.png)

Probably the easiest solution would be to amend `css/sg-style.css` like this:

```css 
.sg-nav-group a,
.sg-nav-group a:visited { … }

.sg-nav-group a:hover,
.sg-nav-group a:focus { … }
```

**Comment by bjankord** [comment]
That makes sense, will plan on adding this code over the weekend

**Comment by bjankord** [comment]
Thanks @yellowled, this has been [added in v3.3.0](https://github.com/bjankord/Style-Guide-Boilerplate/commit/70ec06338839ba428e4a2cfab9a0170fdc212121)

**Comment by yellowled** [comment]
:+1:
